package ar.edu.untref.aydoo;

public enum Provincia {
    SANLUIS, CATAMARCA, BUENOSAIRES, CHACO, CHUBUT, CORDOBA, CORRIENTES, ENTRERIOS, FORMOS, JUJUY, LAPAMPA, LARIOJA, MENDOZA, MISIONES, NEUQUEN, RIONEGRO,SALTA, SANJUAN, SANTACRUZ, SANTAFE,SANTIAGODELESTERO, TIERRADELFUEGO, TUCUMAN
}
